name: libadwaita
description: Libadwaita's widgets for Flutter. Following Gnome HIG and available on all platforms.
version: 2.0.0
homepage: https://github.com/gtk-flutter/libadwaita

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  dbus: ">=0.7.4 <1.0.0"
  flutter:
    sdk: flutter
  flutter_svg: ">=2.0.6 <3.0.0"
  gsettings: ">=0.2.7 <1.0.0"
  libadwaita_core: ">=0.5.4 <2.0.0"
  package_info_plus: ">=4.0.0 <5.0.0"
  popover_gtk: ">=0.2.6+3 <1.0.0"
  url_launcher: ">=6.1.11 <7.0.0"

dev_dependencies:
  very_good_analysis: ^3.0.1

flutter:
  assets:
    - assets/icons/
